### ISSUE TITLE
ClassMopper requires that the library can be found in the @INC path

### ISSUE THREAD

**Issue by cazador481** [ew73/ClassMopper#13]
When using ClassMopper with a library that hasn't been installed, you get an error saying the library isn't in the @INC path.  This makes this very hard to use with dist::zilla's build process.  You can get the filename from the PPI document via the filename subroutine.
When you have that you can do a require of that filename

**Comment by karenetheridge** [comment]
During Dist::Zilla builds, all local modules are in `blib`. You shouldn't be using the copy of the file in `lib`, as that hasn't gone through the build process to have necessary content added such as $VERSION, etc.  The file in lib/ isn't even necessary a compilable perl module yet (e.g. it may have to go through a munging pass).

**Comment by cazador481** [comment]
I will try changing it to blib, and make sure it works, and then update the pull request

**Comment by karenetheridge** [comment]
But `blib` is already in `@INC`... could you provide more details of the original problem, including a stack trace?

**Comment by cazador481** [comment]
Sure, the problem is when I try add ClassMopper to the weaver.ini, and run dzil build the method's, and attributes aren't added.  I did find that if I happen to have the module installed on the system perl it will give me the methods/attributes of the installed perl.  I took the ClassMopper module and printed out the @INC and got the following
$VAR1 = '/home/utils/perl5/perlbrew/perls/5.20.1-008/lib/site_perl/5.20.1/x86_64-linux';
$VAR2 = '/home/utils/perl5/perlbrew/perls/5.20.1-008/lib/site_perl/5.20.1';
$VAR3 = '/home/utils/perl5/perlbrew/perls/5.20.1-008/lib/5.20.1/x86_64-linux';
$VAR4 = '/home/utils/perl5/perlbrew/perls/5.20.1-008/lib/5.20.1';
$VAR5='.'

I get the following error.
Can't locate lsf_deamon.pm in @INC (you may need to install the lsf_deamon module) (@INC contains: /home/nv/lib/perl5 ./inc /home/utils/perl5/perlbrew/perls/5.20.1-008/lib/site_perl/5.20.1/x86_64-linux /home/utils/perl5/perlbrew/perls/5.20.1-008/lib/site_perl/5.20.1 /home/utils/perl5/perlbrew/perls/5.20.1-008/lib/5.20.1/x86_64-linux /home/utils/perl5/perlbrew/perls/5.20.1-008/lib/5.20.1 .) at /home/utils/perl5/perlbrew/perls/5.20.1-008/lib/site_perl/5.20.1/Dist/Zilla/Plugin/PodWeaver.pm line 148.

**Comment by cazador481** [comment]
As an FYI, adding blib works perfectly.

**Comment by karenetheridge** [comment]
ah of course, I see now -- the PodWeaver plugin is running during the FileMunger phase, which is much earlier than when it adds blib to `@INC` for testing.

**Comment by cazador481** [comment]
So should we stick with using the blib path, or go back to using the lib path?

**Comment by karenetheridge** [comment]
Outside of Dist::Zilla, blib is more correct - that's the actual file that was seen by `make` and will be in the shipped dist.

In the Dist::Zilla context, neither blib nor lib is correct -- the file source really ought to be the file content being built up in memory - that is  `map { $_->content } @{ $zilla->files }` - so the plugin should detect it's being run under Dist::Zilla and obtain the zilla object from the hash it was passed in.

**Comment by cazador481** [comment]
I update the pull request with blib.  Can you moose load the file from
memory?  Also if the file uses other files in the dzil package, I an not
sure if that method would pick it up.

**Comment by ew73** [comment]
Thanks, both.  I've let this thing stagnate for a while, apologies.  The changes are merged.  I'll update the tests and push it up to CPAN this weekend.
